### PR TITLE
Merge PR and do a couple of chrome fixes

### PR DESCRIPTION
**Pull request by mudulo**

### CODE REVIEW

**Comment by mudulo** [comment]
HI @TomasHubelbauer I have merged your changes upstream and edited the README file to reflect the same, you could check through if i've done it right. There are issues on Firefox, I'm working on them.

**Comment by TomasHubelbauer** [comment]
Hey, you recovered the original screenshot, but since now `title` is used, it should look as in my screenshot and not the one that is currently in the readme, right? BTW I am using my fork in Firefox without any issues. What issues are you running into? I might be able to help.

**Comment by TomasHubelbauer** [comment]
Also, I removed the extension store links in my fork because at the time of writing I did not know if you'd be interested in my changes so I assumed the fork would live standalone and since my fork is not publishing store builds, I removed the links. Now that my changes are merged here, I think you should return the store links, but we should also cut new builds so that the extensions on the store reflects the updated source code. We need to test that this still works in Chrome and Firefox from the same source code, but it should.

**Comment by mudulo** [comment]
I hadn't realised that you had change the screenshot, so i had tried to generate one after running your code 😂, but I reverted to yours, its up now

**Pull request merged**
